packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@types/eslint-plugin-tailwindcss": ^3.17.0
  "@vitejs/plugin-react": ^4.3.4
  "@t3-oss/env-nextjs": ^0.11.1
  eslint-plugin-tailwindcss: ^3.17.5
  eslint: ^9.17.0
  lucide-react: ^0.469.0
  prettier: ^3.4.2
  tailwindcss: ^3.4.17
  typescript: ^5.6.3
  vite: ^6.0.5
  zod: ^3.24.1

catalogs:
  react19:
    "@types/react": ^19.0.2
    "@types/react-dom": ^19.0.2
    react-dom: ^19.0.0
    react: ^19.0.0
