packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.15.0
  prettier: ^3.3.3
  tailwindcss: ^3.4.13
  typescript: ^5.6.2
  vite: ^5.4.11
  zod: ^3.23.8
  "@vitejs/plugin-react": ^4.3.3

catalogs:
  react18:
    react: ^18.3.1
    react-dom: ^18.3.1
    "@types/react": ^18.3.12
    "@types/react-dom": ^18.3.1
