packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@vitejs/plugin-react": ^4.3.3
  eslint: ^9.16.0
  lucide-react: ^0.460.0
  prettier: ^3.4.1
  tailwindcss: ^3.4.15
  typescript: ^5.6.3
  vite: ^5.4.11
  zod: ^3.23.8

catalogs:
  react18:
    "@types/react": ^18.3.12
    "@types/react-dom": ^18.3.1
    react-dom: ^18.3.1
    react: ^18.3.1
